### ISSUE TITLE
Domain for Liquibase changesets

### ISSUE THREAD

**Issue by mks-d** [mekomsolutions/openmrs-module-initializer#101]

**Comment by mseaton** [comment]
@reagan-meant - at PIH, in our PIH EMR distribution, we have some custom code to execute liquibase changsets that we run immediately before loading metadata from Initializer.  So I would expect that we would add a new "liquibase" domain to Initializer and that it would be the first domain loaded.

Since liquibase xml files can contain references to other liquibase xml files (using the include tag), I would not expect us to support loading any file in this directory, but rather support one specific file that the loader would load (called "liquibase.xml").  It would then be up to this loader to include other files at relative paths as appropriate.

So the simple implementation of this loader would extend BaseFileLoader, and would implement the load(File) method something like this:

```
if (the file being loads is named "liquibase.xml" and is at the root of the domain directory) {
  DatabaseUpdater.executeChangelog(file.getAbsolutePath(), null);
}
```

**Comment by rbuisson** [comment]
Thanks for detailing your requirement and techincal approach @mseaton !

So to summarize:
- Add a `liquibase` domain
- Make sure it runs before every other domain
- Assume only 1 file in the domain: **liquibase.xml**. Loading additional files should be handled directly by the Liquibase engine.
- Add unit tests
- Add documentation.

**Comment by rbuisson** [comment]
Hi @Ruhanga , I'm assigning you to this ticket. Priority is end of the month.
Is this ok with you?

**Comment by mseaton** [comment]
Yes, that sounds good.  To be clear there may be other files in the domain directory, but the only file that the loader needs to directly concern itself with is the one called "liquibase.xml".

**Comment by Ruhanga** [comment]
>Priority is end of the month.
Is this ok with you?

Fair enough @rbuisson. Thanks all.
