### ISSUE TITLE
Program workflow state loader fails to find unique non-retired workflow

### ISSUE THREAD

**Issue by brandones** [mekomsolutions/openmrs-module-initializer#127]
The workflow state loader looks up a workflow by concept, using the function [fetchProgramWorkflow](https://github.com/mekomsolutions/openmrs-module-initializer/blob/752edb1b5371208d6db0020de65c8c02db6855de/api/src/main/java/org/openmrs/module/initializer/api/utils/Utils.java#L354).

This function calls [getProgramWorkflowsByConcept](https://github.com/openmrs/openmrs-core/blob/f76ee93cc46271997e577ed7fa223ac4a4e53dcb/api/src/main/java/org/openmrs/api/db/hibernate/HibernateProgramWorkflowDAO.java#L380), which returns all workflows matching that concept, both retired and un-retired.

`fetchProgramWorkflow` returns `null` if more than one workflow is found. Problematically, it will return `null` when two workflows are found, which can happen if one of them is retired.

**Comment by mseaton** [comment]
@brandones / @mks-d - I disagree with this ticket and the PR proposed to fix it.  A retired piece of metadata does not render it invalid or undesirable, and one may have legitimate reasons to associate retired metadata (concepts, etc) with other metadata.  If one's concept dictionary is such that referring to a concept by name or mapping is not sufficiently unique to allow that name or mapping to be used as an identifier, then the implementer always has the ability to use the uuid - which is 100% unique and reliable - or to change the name / remove the mapping of the old concept that is being retired so that it no longer conflicts.  So I would personally mark this as "Won't Fix".  @mogoodrich FYI

**Comment by mogoodrich** [comment]
It's a good point @mseaton   As a practical example of how this good be a problem, what if you had an existing program state or workflow you wanted to retire, but at the same time create a new state or workflow using the same concept?
