### ISSUE TITLE
Concept references should support names in locales other than the default locale

### ISSUE THREAD

**Issue by brandones** [mekomsolutions/openmrs-module-initializer#194]
In OpenMRS there is no requirement that concepts have an FSN, or any name at all, in the default locale. Initializer should not have this requirement either.

It should be possible to load a CSV where the concepts refer to each others' English FSNs into a server where the default locale is Spanish.

My proposed solution is a special header, like the version header, that would set the locale for the file, e.g. `_locale: en`.

**Comment by mseaton** [comment]
I agree with @brandones that Initializer should not fail to find a concept that is able to be identified by name, just because that name is not in the default Context locale.  My alternative proposal is to change the logic for how we look up concepts.  The current logic is:

1. Try to find by uuid
2. If null, try to find by name in the Context.getLocale()
3. If null, try to find by mapping

My proposed alternative is to make a few changes to this:

1. Try to find by uuid
2. If null, try to find by mapping (mapping should be preferred over name)
3. If null, try to find by name:
  - Get all of the supported locales in the system, in preferred order (core has a method for this)
  - Iterate over these locales, and look up the concept by name in the given locale
  - If found, return it.  If not found, continue iterating to the next locale in order
4. If still not found, return null

Because the core method - LocaleUtility.getLocalesInOrder() - returns Context.getLocale() as the first locale to check, this will initially have the same behavior as currently.    Only if the concept still isn't found at this point will it move on to check if the concept can be found adequately using other supported system Locales.

@mogoodrich / @mks-d / @ibacher let me know your thoughts.  PR imminent.

**Comment by ibacher** [comment]
@mseaton I like most of this. I'm a little hesitant about the mapping, depending on how that's implemented, mostly because it should be possible to have multiple concepts that map to the same mapping (e.g., for integration with external systems). I agree that mappings are the right way to identify concepts; I just think we need some kind of way of demarcating the canonical mapping for a concept.

The difference I'm imagining is this: inside, e.g., a PIH system, it makes sense that `PIH:YES` always refers to the same concept and if you load a concept with the mapping `PIH:YES`, it's probably intended to replace the existing `PIH:YES` concept. However, if I have a concept that's mapped to an "external" source, e.g., LOINC or SNOMED, that's probably so I can exchange data with external systems and I may have more than one concept that maps to the same LOINC code, e.g., because two different programs have different display preferences for the name of the test even though to the lab they're the same test. In those cases, we shouldn't clobber the existing concept.

I fully agree with the name algorithm and the `LocaleUtility.getLocalesInOrder()` is definitely the right way to go.

**Comment by mseaton** [comment]
Thanks @ibacher for the feedback.  The mapping behavior is not something I'm newly introducing, we've always allowed looking up concepts by mapping.  I'm just proposing we move it ahead of looking up by name, as mapping should be preferred over name for referring to a concept generally.

Regarding your concerns, this functionality is only really used when looking up a concept-related column in a CSV, not for determining whether to override a given Concept definition or not.  For example, if I have a drugs CSV, a programs CSV, or a conceptset CSV, and I want to indicate what Concept a drug, program, or set membership is associated with, this is where this is used.  So one could use the concept uuid, mapping, or name to indicate what concept is being referred to.  It's an active choice by someone who is authoring a CSV to use a particular mapping source:code combination as an identifier, it isn't implicit in the module.

**Comment by mseaton** [comment]
PR raised here:  #197

**Comment by mogoodrich** [comment]
A *ping* on this one... :)
