### ISSUE TITLE
Support for OCL export ZIP file.

### ISSUE THREAD

**Issue by mks-d** [mekomsolutions/openmrs-module-initializer#96]

**Comment by gracepotma** [comment]
OMRS Ticket ID: https://issues.openmrs.org/browse/OCLOMRS-950 

Notes page: https://docs.google.com/document/d/1UGFYMRawyfOpVqnxuI1YzrPsdMR0pi8z3_Ze-0ixTGM/edit

Additional Use Case Details: 
- **Enable Concepts to be loaded into Iniz that are managed in OCLOMRS**. Have Iniz use Subscription Module. Looking into loader Iniz using. Goal is to have Iniz understand the OCL .zip file (and the JSON file inside).
- (confirm check-sum is ok) Iniz uses a check-sum to determine whether or not to re-load a file - so whatever we put into Iniz, if it's the same content, then ideally it would have the same check-sum
- **Support offline (and reasonable file size)**. Will support offline loading needs as well / "deploy with USB stick" scenario. (currently 18MB pretty & zipped)
- **Support diff check/review of JSON file** (user friendly to look at). The OCL .zip may not have been originally designed with that use case in mind. JSON needs to be formatted nicely enough, with predictable order, so that diffs/review would be relatively easy. (e.g. if you produce it 3 times, you get the properties in the same order every time). → May need update to OCL Module to support unzipped or zipped file.

**Comment by ibacher** [comment]
Closing as #100 was merged.
